var productos = [
  {
    nombre: "Mancuernas Ajustables 2x20kg",
    precio: 189.99,
    stock: 25,
    marca: "IronPro",
    categoria: "Fuerza",
    descCorta: "Mancuernas regulables de acero",
    descLarga: "Set de dos mancuernas ajustables con discos intercambiables de acero, agarre antideslizante y seguro de rosca.",
    edadDesde: 16,
    edadHasta: null,
    foto: "https://helisports.pictures/products/1000/newton-fitness/adjustable-dumbbells/rubber-30mm/2x20kg/newton-fitness-rubber-adjustable-dumbell-2x20kg.jpg",
    envio: true
  },
  {
    nombre: "Banda Elástica de Resistencia",
    precio: 12.50,
    stock: 100,
    marca: "FlexFit",
    categoria: "Entrenamiento Funcional",
    descCorta: "Banda elástica nivel medio",
    descLarga: "Banda de resistencia ideal para entrenamiento funcional, rehabilitación y tonificación muscular. Hecha de látex natural.",
    edadDesde: 12,
    edadHasta: null,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPEIHq3ktqOsb-pJoxJhN6k6EaTSbjkL7GUg&s",
    envio: true
  },
  {
    nombre: "Colchoneta Yoga Antideslizante",
    precio: 29.90,
    stock: 50,
    marca: "ZenMat",
    categoria: "Yoga y Pilates",
    descCorta: "Colchoneta 6mm",
    descLarga: "Colchoneta antideslizante de 6mm de espesor, ideal para yoga, pilates y estiramientos. Material TPE ecológico.",
    edadDesde: null,
    edadHasta: null,
    foto: "https://http2.mlstatic.com/D_NQ_NP_954791-MLA81538094361_122024-O.webp",
    envio: true
  },
  {
    nombre: "Bicicleta Estática ProFit X300",
    precio: 499.99,
    stock: 8,
    marca: "ProFit",
    categoria: "Cardio",
    descCorta: "Bicicleta estática magnética",
    descLarga: "Bicicleta estática profesional con resistencia magnética ajustable, pantalla LCD y pulsómetro integrado.",
    edadDesde: 18,
    edadHasta: null,
    foto: "https://http2.mlstatic.com/D_653229-MLA89165880907_082025-O.jpg",
    envio: false
  },
  {
    nombre: "Chaleco de Peso Ajustable 10kg",
    precio: 74.99,
    stock: 15,
    marca: "PowerWear",
    categoria: "Fuerza",
    descCorta: "Chaleco con bolsillos de peso",
    descLarga: "Chaleco ajustable con compartimentos para distribuir el peso, ideal para entrenamiento funcional y running.",
    edadDesde: 16,
    edadHasta: 60,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlKHEkt1H6j5fp37E059Qjd2wWeexwUW-Iow&s",
    envio: true
  },
  {
    nombre: "Cinta de Correr ProRun 5000",
    precio: 799.99,
    stock: 10,
    marca: "ProRun",
    categoria: "Cardio",
    descCorta: "Cinta eléctrica con inclinación automática.",
    descLarga: "Cinta de correr con 15 niveles de inclinación, 20 programas, velocidad de hasta 20 km/h y pantalla LCD.",
    foto: "https://m.media-amazon.com/images/I/41AK2ZnDkZL._UF1000,1000_QL80_.jpg",
    envio: true,
    edadDesde: 16,
    edadHasta: null
  },
  {
    nombre: "Zapatillas Running AirFlex",
    precio: 119.99,
    stock: 50,
    marca: "AirFlex",
    categoria: "Calzado",
    descCorta: "Zapatillas ligeras y transpirables.",
    descLarga: "Diseñadas para largas distancias, con amortiguación reactiva y suela antideslizante.",
    foto: "https://media2.solodeportes.com.ar/media/catalog/product/cache/7c4f9b393f0b8cb75f2b74fe5e9e52aa/z/a/zapatillas-running-nike-air-zoom-pegasus-40-negra-510010dv3853001-1_1.jpg",
    envio: true,
    edadDesde: 12,
    edadHasta: null
  },
  {
    nombre: "Reloj Deportivo ChronoMax X10",
    precio: 149.99,
    stock: 40,
    marca: "ChronoMax",
    categoria: "Accesorios",
    descCorta: "Reloj deportivo con cronómetro y monitoreo cardíaco.",
    descLarga: "Incluye GPS integrado, seguimiento de pasos, calorías, distancia y resistencia al agua hasta 50 metros.",
    foto: "https://okeyrosario.com.ar/wp-content/uploads/2024/01/x10-max-1.jpg",
    envio: true,
    edadDesde: 12,
    edadHasta: null
  },
  {
    nombre: "Camiseta Deportiva DryFit Pro",
    precio: 29.99,
    stock: 100,
    marca: "DryFit",
    categoria: "Ropa deportiva",
    descCorta: "Camiseta transpirable y ligera.",
    descLarga: "Fabricada en tela DryFit para mantenerte seco y cómodo durante el entrenamiento.",
    foto: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw22315c38/products/NI_DD1992-011/NI_DD1992-011-1.jpg",
    envio: true,
    edadDesde: null,
    edadHasta: null
  }
];
